#!/bin/bash

# CLEANUP for testing 
rm -rf /tmp/Addons
# Install addons 
wget -i addons -P /tmp/Addons

# Unzip addons
unzip /tmp/Addons/"*.zip" -d /tmp/Addons

# remove the zip archives 
find /tmp/Addons -maxdepth 1 -type f -name "*.zip" -delete
find /tmp/Addons -maxdepth 1 -type f -name "*.zip.*" -delete



